# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
