# Generated by Django 2.1.3 on 2018-11-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoUser',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='solved',
        ),
    ]
