# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['points', 'display_name']},
        ),
    ]
