version: "3.3"
services:
  scoreboard:
    build: scoreboard
    depends_on: [database]
    ports: ['80:80']
    volumes: ['./data/secrets:/secrets']
  database:
    image: postgres
    volumes: ['./data/database:/var/lib/postgresql/data']
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  web-clicks:
    build: challenges/web-clicks
    ports: ['127.0.0.1:9001:80']
  crypto-tags:
    build: challenges/crypto-tags
    ports: ['127.0.0.1:9002:80']
  web-admin:
    build: challenges/web-admin
    ports: ['127.0.0.1:9003:8888']
  crypto-algebraic:
    build: challenges/crypto-algebraic
    ports: ['127.0.0.1:9004:8888']
  web-call:
    build: challenges/web-call
    ports: ['127.0.0.1:9005:8888']
  python-zero:
    build: challenges/python-zero
    ports: ['127.0.0.1:9006:8888']
  python-alphabet:
    build: challenges/python-alphabet
    ports: ['127.0.0.1:9007:8888']
  python-setup:
    build: challenges/python-setup
    ports: ['127.0.0.1:9008:8888']
  python-arguments:
    build: challenges/python-arguments
    ports: ['127.0.0.1:9009:8888']
  python-sandbox:
    build: challenges/python-sandbox
    ports: ['127.0.0.1:9010:8888']
  python-yam:
    build: challenges/python-yam
    ports: ['127.0.0.1:9011:8888']
  python-format:
    build: challenges/python-format
    ports: ['127.0.0.1:9012:8888']
  web-sqli:
    build: challenges/web-sqli
    ports: ['127.0.0.1:9013:8888']
  web-sequel:
    build: challenges/web-sequel
    ports: ['127.0.0.1:9014:8888']
  web-hidden:
    build: challenges/web-hidden
    ports: ['127.0.0.1:9015:80']
  web-guestbook:
    build: challenges/web-guestbook
    ports: ['127.0.0.1:9016:8888']
    security_opt: ['seccomp:./config/seccomp/ctf.json']
  python-code:
    build: challenges/python-code
    ports: ['127.0.0.1:9017:8888']
  python-underscore:
    build: challenges/python-underscore
    ports: ['127.0.0.1:9020:8888']
